FROM openjdk
WORKDIR usr/lib
ADD ./target/BEJ_C3_S2_Containerize_Using_Docker_MC_1-0.0.1-SNAPSHOT.jar /usr/lib/BEJ_C3_S2_Containerize_Using_Docker_MC_1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","BEJ_C3_S2_Containerize_Using_Docker_MC_1-0.0.1-SNAPSHOT.jar"]
